highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://shuhanggu.github.io/
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /homepage/
title: Homepage of Shuhang Gu
name: Shuhang Gu
email: shuhanggu@gmail.com
email_full: mailto:shuhanggu@gmail.com
website: github.com/ShuhangGu
website_full: https://github.com/ShuhangGu

#address:
#  street: 135 Yaguan Road
#  postcode: 300350
#  city: Tianjin
#  country: China

# needed for travis-ci build
exclude: [vendor]
