highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://shuhanggu.github.io/
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Homepage of Shuhang Gu
name: Shuhang Gu
email: shuhanggu@gmail.com  
email_full: mailto:shuhanggu@gmail.com  
website: github.com/ShuhangGu
website_full: https://github.com/ShuhangGu

address:
  Office: ETF C115,
  street: Sternwartstrasse 7, ETH Zentrum
  postcode: 8092
  city: Zurich
  country: Switzerland

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-cayman